# Generated by Django 3.1.3 on 2020-11-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url_mappings',
            new_name='UrlMappings',
        ),
        migrations.RenameField(
            model_name='urlmappings',
            old_name='short_url',
            new_name='short_path',
        ),
    ]
